use std::collections::HashSet;

use crate::engine::CellCoord;

pub fn hex_map() -> HashSet<CellCoord> {
    vec![
        //CellCoord { x: 2, y: -5, z: 3 },
        CellCoord { x: -5, y: -4, z: 9 },
        CellCoord { x: 3, y: 3, z: -6 },
        CellCoord { x: 6, y: 3, z: -9 },
        CellCoord { x: -7, y: -1, z: 8 },
        //CellCoord { x: 1, y: -3, z: 2 },
        CellCoord { x: -10, y: 3, z: 7 },
        //CellCoord { x: -6, y: 8, z: -2 },
        CellCoord { x: -3, y: -5, z: 8 },
        //CellCoord { x: -8, y: 3, z: 5 },
        //CellCoord { x: -8, y: 8, z: 0 },
        ////CellCoord { x: -3, y: -2, z: 5 },
        CellCoord { x: -2, y: 0, z: 2 },
        //CellCoord { x: 3, y: -7, z: 4 },
        CellCoord { x: -2, y: 5, z: -3 },
        //CellCoord { x: -3, y: -6, z: 9 },
        CellCoord {
            x: -8,
            y: 10,
            z: -2,
        },
        CellCoord { x: 2, y: -2, z: 0 },
        CellCoord { x: -2, y: 9, z: -7 },
        CellCoord { x: -1, y: -8, z: 9 },
        CellCoord { x: 3, y: 0, z: -3 },
        CellCoord { x: -4, y: -1, z: 5 },
        CellCoord { x: 5, y: -1, z: -4 },
        CellCoord { x: 6, y: -9, z: 3 },
        CellCoord { x: 8, y: -2, z: -6 },
        CellCoord { x: -5, y: -2, z: 7 },
        CellCoord { x: 3, y: -8, z: 5 },
        CellCoord { x: -8, y: 9, z: -1 },
        CellCoord {
            x: -3,
            y: -7,
            z: 10,
        },
        CellCoord { x: 9, y: -5, z: -4 },
        CellCoord { x: -10, y: 5, z: 5 },
        CellCoord { x: 4, y: -8, z: 4 },
        CellCoord { x: -6, y: 6, z: 0 },
        CellCoord { x: -1, y: 1, z: 0 },
        CellCoord {
            x: 10,
            y: -9,
            z: -1,
        },
        CellCoord { x: -8, y: 7, z: 1 },
        CellCoord { x: 9, y: -3, z: -6 },
        CellCoord { x: 5, y: 2, z: -7 },
        CellCoord { x: 8, y: -5, z: -3 },
        CellCoord { x: -4, y: 6, z: -2 },
        CellCoord { x: 5, y: -4, z: -1 },
        CellCoord { x: 2, y: -1, z: -1 },
        CellCoord { x: -10, y: 2, z: 8 },
        CellCoord { x: -7, y: 2, z: 5 },
        CellCoord { x: 2, y: 5, z: -7 },
        CellCoord { x: 9, y: 0, z: -9 },
        CellCoord { x: 6, y: -6, z: 0 },
        CellCoord {
            x: 10,
            y: -3,
            z: -7,
        },
        CellCoord { x: -7, y: 0, z: 7 },
        CellCoord { x: 0, y: 4, z: -4 },
        CellCoord { x: 2, y: 8, z: -10 },
        CellCoord { x: 7, y: -7, z: 0 },
        CellCoord {
            x: -7,
            y: 10,
            z: -3,
        },
        CellCoord { x: -3, y: 3, z: 0 },
        CellCoord { x: 6, y: 4, z: -10 },
        CellCoord { x: -10, y: 4, z: 6 },
        CellCoord { x: 7, y: 2, z: -9 },
        CellCoord { x: 6, y: -4, z: -2 },
        CellCoord { x: 1, y: -6, z: 5 },
        CellCoord {
            x: -5,
            y: -5,
            z: 10,
        },
        CellCoord { x: -1, y: 8, z: -7 },
        CellCoord { x: 7, y: -5, z: -2 },
        CellCoord { x: 7, y: -1, z: -6 },
        CellCoord { x: -9, y: 1, z: 8 },
        CellCoord { x: -8, y: 0, z: 8 },
        CellCoord { x: 0, y: -4, z: 4 },
        CellCoord { x: 8, y: -8, z: 0 },
        CellCoord { x: -9, y: 9, z: 0 },
        CellCoord { x: -5, y: 1, z: 4 },
        CellCoord { x: -6, y: -1, z: 7 },
        CellCoord { x: 1, y: 3, z: -4 },
        CellCoord { x: 4, y: 5, z: -9 },
        CellCoord { x: 5, y: 0, z: -5 },
        CellCoord { x: 3, y: 2, z: -5 },
        CellCoord { x: -3, y: -3, z: 6 },
        CellCoord { x: -7, y: 8, z: -1 },
        CellCoord { x: -6, y: 3, z: 3 },
        CellCoord { x: 8, y: 2, z: -10 },
        CellCoord { x: 4, y: 0, z: -4 },
        CellCoord {
            x: 10,
            y: -7,
            z: -3,
        },
        CellCoord { x: -1, y: -5, z: 6 },
        CellCoord { x: 2, y: -8, z: 6 },
        CellCoord { x: 9, y: -8, z: -1 },
        CellCoord {
            x: -1,
            y: -9,
            z: 10,
        },
        CellCoord {
            x: -10,
            y: 10,
            z: 0,
        },
        CellCoord { x: 5, y: -9, z: 4 },
        CellCoord { x: -1, y: -1, z: 2 },
        CellCoord { x: -9, y: 6, z: 3 },
        CellCoord { x: -6, y: 4, z: 2 },
        CellCoord { x: -1, y: 0, z: 1 },
        CellCoord {
            x: -4,
            y: -6,
            z: 10,
        },
        CellCoord {
            x: -2,
            y: -8,
            z: 10,
        },
        CellCoord { x: 3, y: -5, z: 2 },
        //CellCoord { x: -7, y: 4, z: 3 },
        //CellCoord { x: -3, y: 5, z: -2 },
        //CellCoord { x: -7, y: 5, z: 2 },
        //CellCoord { x: -6, y: 2, z: 4 },
        //CellCoord { x: 0, y: 0, z: 0 },
        //CellCoord { x: 0, y: -8, z: 8 },
        //CellCoord { x: 0, y: -3, z: 3 },
        //CellCoord { x: 1, y: -7, z: 6 },
        //CellCoord { x: 3, y: 5, z: -8 },
        //CellCoord { x: 5, y: -2, z: -3 },
        //CellCoord { x: 6, y: -8, z: 2 },
        CellCoord { x: 4, y: -9, z: 5 },
        CellCoord { x: -3, y: -1, z: 4 },
        CellCoord { x: 2, y: -7, z: 5 },
        CellCoord { x: 8, y: -6, z: -2 },
        CellCoord { x: -7, y: 3, z: 4 },
        CellCoord { x: 5, y: -5, z: 0 },
        CellCoord {
            x: 10,
            y: -2,
            z: -8,
        },
        CellCoord { x: -1, y: 9, z: -8 },
        CellCoord { x: -2, y: -1, z: 3 },
        CellCoord { x: -9, y: 8, z: 1 },
        CellCoord { x: -6, y: 7, z: -1 },
        CellCoord { x: 3, y: -6, z: 3 },
        CellCoord { x: 9, y: -9, z: 0 },
        CellCoord { x: -9, y: 2, z: 7 },
        CellCoord { x: -7, y: 9, z: -2 },
        CellCoord { x: 4, y: 3, z: -7 },
        CellCoord { x: -5, y: 0, z: 5 },
        CellCoord { x: -7, y: -2, z: 9 },
        CellCoord { x: -3, y: 9, z: -6 },
        CellCoord { x: -2, y: 3, z: -1 },
        CellCoord { x: 5, y: 1, z: -6 },
        CellCoord { x: -4, y: 9, z: -5 },
        CellCoord { x: 8, y: 1, z: -9 },
        CellCoord { x: -4, y: 0, z: 4 },
        CellCoord { x: 2, y: 1, z: -3 },
        CellCoord { x: -1, y: -7, z: 8 },
        CellCoord { x: 1, y: -4, z: 3 },
        CellCoord { x: 4, y: -1, z: -3 },
        CellCoord { x: 2, y: 3, z: -5 },
        CellCoord { x: -6, y: -3, z: 9 },
        CellCoord { x: -4, y: 3, z: 1 },
        CellCoord { x: 1, y: 7, z: -8 },
        CellCoord { x: 3, y: -10, z: 7 },
        CellCoord { x: 1, y: 6, z: -7 },
        CellCoord { x: -3, y: 0, z: 3 },
        CellCoord { x: -1, y: -2, z: 3 },
        CellCoord { x: 1, y: 8, z: -9 },
        CellCoord { x: 0, y: 2, z: -2 },
        CellCoord { x: -10, y: 8, z: 2 },
        CellCoord { x: 0, y: -9, z: 9 },
        CellCoord { x: 7, y: -8, z: 1 },
        CellCoord { x: -10, y: 1, z: 9 },
        CellCoord { x: -4, y: 5, z: -1 },
        CellCoord { x: 6, y: -3, z: -3 },
        CellCoord { x: -8, y: 5, z: 3 },
        CellCoord { x: 7, y: -6, z: -1 },
        CellCoord { x: 9, y: -6, z: -3 },
        CellCoord { x: 7, y: 0, z: -7 },
        CellCoord { x: 8, y: -7, z: -1 },
        CellCoord { x: 4, y: -5, z: 1 },
        CellCoord { x: -8, y: -1, z: 9 },
        CellCoord { x: 7, y: -2, z: -5 },
        CellCoord { x: 5, y: -10, z: 5 },
        CellCoord { x: 2, y: -6, z: 4 },
        CellCoord { x: 1, y: -9, z: 8 },
        CellCoord { x: 3, y: -2, z: -1 },
        CellCoord { x: -6, y: -2, z: 8 },
        CellCoord { x: -2, y: 8, z: -6 },
        CellCoord {
            x: -8,
            y: -2,
            z: 10,
        },
        CellCoord { x: -7, y: 7, z: 0 },
        CellCoord { x: -5, y: 9, z: -4 },
        CellCoord { x: 1, y: 4, z: -5 },
        CellCoord { x: -1, y: 5, z: -4 },
        CellCoord { x: 2, y: 0, z: -2 },
        CellCoord { x: 7, y: -3, z: -4 },
        CellCoord { x: 4, y: 6, z: -10 },
        CellCoord { x: -9, y: 4, z: 5 },
        CellCoord {
            x: -9,
            y: 10,
            z: -1,
        },
        CellCoord { x: 0, y: -1, z: 1 },
        CellCoord {
            x: 10,
            y: -4,
            z: -6,
        },
        CellCoord { x: 0, y: 9, z: -9 },
        CellCoord { x: 3, y: 7, z: -10 },
        CellCoord { x: 4, y: -6, z: 2 },
        CellCoord { x: 4, y: -2, z: -2 },
        CellCoord { x: -4, y: -4, z: 8 },
        CellCoord { x: 2, y: -10, z: 8 },
        CellCoord { x: 4, y: -3, z: -1 },
        CellCoord { x: 9, y: -1, z: -8 },
        CellCoord {
            x: 0,
            y: 10,
            z: -10,
        },
        CellCoord {
            x: -7,
            y: -3,
            z: 10,
        },
        CellCoord { x: -5, y: 4, z: 1 },
        CellCoord { x: 2, y: 4, z: -6 },
        CellCoord { x: 3, y: -1, z: -2 },
        CellCoord { x: -2, y: -2, z: 4 },
        CellCoord { x: 5, y: -8, z: 3 },
        CellCoord { x: -1, y: 4, z: -3 },
        CellCoord { x: -7, y: 6, z: 1 },
        CellCoord { x: -4, y: -2, z: 6 },
        CellCoord { x: -1, y: -6, z: 7 },
        CellCoord { x: -2, y: 7, z: -5 },
        CellCoord { x: 8, y: 0, z: -8 },
        CellCoord { x: 1, y: -2, z: 1 },
        CellCoord { x: -3, y: 4, z: -1 },
        CellCoord { x: 2, y: -3, z: 1 },
        CellCoord { x: -3, y: 8, z: -5 },
        CellCoord { x: 3, y: 4, z: -7 },
        CellCoord { x: 0, y: -7, z: 7 },
        CellCoord {
            x: 10,
            y: 0,
            z: -10,
        },
        CellCoord { x: 1, y: 2, z: -3 },
        CellCoord { x: 4, y: -10, z: 6 },
        CellCoord {
            x: 10,
            y: -1,
            z: -9,
        },
        CellCoord { x: 3, y: -9, z: 6 },
        CellCoord { x: -2, y: -5, z: 7 },
        CellCoord { x: -10, y: 6, z: 4 },
        CellCoord { x: 2, y: 2, z: -4 },
        CellCoord { x: -9, y: 3, z: 6 },
        CellCoord { x: 6, y: -2, z: -4 },
        CellCoord { x: 6, y: -10, z: 4 },
        CellCoord {
            x: 10,
            y: -6,
            z: -4,
        },
        CellCoord { x: 0, y: 1, z: -1 },
        CellCoord { x: -5, y: -1, z: 6 },
        CellCoord {
            x: -1,
            y: 10,
            z: -9,
        },
        CellCoord { x: -4, y: 7, z: -3 },
        CellCoord {
            x: -6,
            y: 10,
            z: -4,
        },
        CellCoord { x: -3, y: 1, z: 2 },
        CellCoord { x: 5, y: -6, z: 1 },
        CellCoord { x: 5, y: -3, z: -2 },
        CellCoord { x: 8, y: -10, z: 2 },
        CellCoord {
            x: 10,
            y: -8,
            z: -2,
        },
        CellCoord { x: -5, y: 6, z: -1 },
        CellCoord { x: 3, y: -3, z: 0 },
        CellCoord { x: 0, y: -6, z: 6 },
        CellCoord { x: -10, y: 9, z: 1 },
        CellCoord { x: -10, y: 7, z: 3 },
        CellCoord { x: -1, y: -3, z: 4 },
        CellCoord { x: -1, y: 7, z: -6 },
        CellCoord { x: 1, y: 0, z: -1 },
        CellCoord { x: 7, y: -10, z: 3 },
        CellCoord { x: 9, y: -10, z: 1 },
        CellCoord { x: 1, y: -5, z: 4 },
        CellCoord { x: 6, y: 0, z: -6 },
        CellCoord {
            x: -10,
            y: 0,
            z: 10,
        },
        CellCoord {
            x: -3,
            y: 10,
            z: -7,
        },
        CellCoord { x: -3, y: 7, z: -4 },
        CellCoord { x: 0, y: -2, z: 2 },
        CellCoord { x: -4, y: 1, z: 3 },
        CellCoord { x: -5, y: 7, z: -2 },
        CellCoord { x: 2, y: 6, z: -8 },
        CellCoord { x: 0, y: 7, z: -7 },
        CellCoord { x: 0, y: 5, z: -5 },
        CellCoord { x: -4, y: 2, z: 2 },
        CellCoord {
            x: -5,
            y: 10,
            z: -5,
        },
        CellCoord { x: -2, y: -4, z: 6 },
        CellCoord { x: -2, y: -3, z: 5 },
        CellCoord {
            x: 0,
            y: -10,
            z: 10,
        },
        CellCoord { x: -5, y: 3, z: 2 },
        CellCoord { x: -2, y: 6, z: -4 },
        CellCoord { x: -1, y: -4, z: 5 },
        CellCoord { x: 1, y: 9, z: -10 },
        CellCoord { x: 3, y: 1, z: -4 },
        CellCoord { x: -8, y: 1, z: 7 },
        CellCoord { x: -6, y: 1, z: 5 },
        CellCoord { x: 7, y: -9, z: 2 },
        CellCoord { x: 5, y: 3, z: -8 },
        CellCoord { x: 6, y: -1, z: -5 },
        CellCoord { x: -9, y: 0, z: 9 },
        CellCoord { x: -8, y: 2, z: 6 },
        CellCoord { x: -7, y: 1, z: 6 },
        CellCoord { x: -2, y: 2, z: 0 },
        CellCoord { x: 0, y: 6, z: -6 },
        CellCoord { x: -5, y: -3, z: 8 },
        CellCoord { x: -5, y: 8, z: -3 },
        CellCoord { x: 4, y: -7, z: 3 },
        CellCoord { x: 9, y: -7, z: -2 },
        CellCoord { x: 9, y: -4, z: -5 },
        CellCoord { x: -6, y: 5, z: 1 },
        CellCoord { x: -3, y: 2, z: 1 },
        CellCoord { x: 4, y: 4, z: -8 },
        CellCoord {
            x: -4,
            y: 10,
            z: -6,
        },
        CellCoord {
            x: 10,
            y: -10,
            z: 0,
        },
        CellCoord { x: 2, y: -4, z: 2 },
        CellCoord { x: 6, y: -5, z: -1 },
        CellCoord { x: -2, y: 1, z: 1 },
        CellCoord { x: -1, y: 2, z: -1 },
        CellCoord { x: -8, y: 6, z: 2 },
        CellCoord { x: -2, y: -6, z: 8 },
        CellCoord { x: 3, y: -4, z: 1 },
        CellCoord { x: 1, y: -1, z: 0 },
        CellCoord { x: 7, y: 3, z: -10 },
        CellCoord { x: -4, y: 4, z: 0 },
        CellCoord { x: 0, y: 8, z: -8 },
        CellCoord { x: -4, y: -5, z: 9 },
        CellCoord { x: -9, y: 5, z: 4 },
        CellCoord { x: 1, y: -8, z: 7 },
        CellCoord { x: -3, y: -4, z: 7 },
        CellCoord { x: 4, y: 1, z: -5 },
        CellCoord { x: 6, y: -7, z: 1 },
        CellCoord { x: -2, y: -7, z: 9 },
        CellCoord { x: 5, y: 5, z: -10 },
        CellCoord {
            x: -9,
            y: -1,
            z: 10,
        },
        CellCoord { x: -4, y: 8, z: -4 },
        CellCoord {
            x: -6,
            y: -4,
            z: 10,
        },
        CellCoord { x: 8, y: -9, z: 1 },
        CellCoord { x: 8, y: -1, z: -7 },
        CellCoord { x: -8, y: 4, z: 4 },
        CellCoord { x: -1, y: 3, z: -2 },
        CellCoord { x: 4, y: 2, z: -6 },
        CellCoord { x: 8, y: -4, z: -4 },
        CellCoord { x: 9, y: 1, z: -10 },
        CellCoord { x: -9, y: 7, z: 2 },
        CellCoord { x: -1, y: 6, z: -5 },
        CellCoord { x: 0, y: 3, z: -3 },
        CellCoord { x: 3, y: 6, z: -9 },
        CellCoord { x: -4, y: -3, z: 7 },
        CellCoord { x: 7, y: 1, z: -8 },
        CellCoord {
            x: -2,
            y: 10,
            z: -8,
        },
        CellCoord { x: 1, y: -10, z: 9 },
        CellCoord { x: 8, y: -3, z: -5 },
        CellCoord { x: 1, y: 5, z: -6 },
        CellCoord { x: 6, y: 1, z: -7 },
        CellCoord { x: 7, y: -4, z: -3 },
        CellCoord { x: -5, y: 2, z: 3 },
        CellCoord { x: 0, y: -5, z: 5 },
        CellCoord { x: 4, y: -4, z: 0 },
        CellCoord { x: 1, y: 1, z: -2 },
        CellCoord { x: 5, y: -7, z: 2 },
        CellCoord {
            x: 10,
            y: -5,
            z: -5,
        },
        CellCoord { x: -6, y: 0, z: 6 },
        CellCoord { x: -6, y: 9, z: -3 },
        CellCoord { x: 2, y: 7, z: -9 },
        CellCoord { x: -5, y: 5, z: 0 },
        CellCoord { x: -2, y: 4, z: -2 },
        CellCoord { x: 2, y: -9, z: 7 },
        CellCoord { x: 5, y: 4, z: -9 },
        CellCoord { x: -3, y: 6, z: -3 },
        CellCoord { x: 6, y: 2, z: -8 },
        CellCoord { x: 9, y: -2, z: -7 },
    ]
    .into_iter()
    .collect()
}
